"""Add sync columns to risk_assessment_logs

Revision ID: 0df4576d0d2f
Revises: 
Create Date: 2024-10-29 18:19:06.682981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df4576d0d2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessment_logs', sa.Column('sync_start_time', sa.DateTime(), nullable=True))
    op.add_column('risk_assessment_logs', sa.Column('sync_end_time', sa.DateTime(), nullable=True))
    op.add_column('risk_assessment_logs', sa.Column('sync_status', sa.String(), nullable=True))
    op.add_column('risk_assessment_logs', sa.Column('sync_error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_assessment_logs', 'sync_error_message')
    op.drop_column('risk_assessment_logs', 'sync_status')
    op.drop_column('risk_assessment_logs', 'sync_end_time')
    op.drop_column('risk_assessment_logs', 'sync_start_time')
    # ### end Alembic commands ###
